/*
Navicat MySQL Data Transfer

Source Server         : localhost
Source Server Version : 50144
Source Host           : 127.0.0.1:3306
Source Database       : ciblog

Target Server Type    : MYSQL
Target Server Version : 50144
File Encoding         : 65001

Date: 2015-09-14 10:31:12
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for `blog_article`
-- ----------------------------
DROP TABLE IF EXISTS `blog_article`;
CREATE TABLE `blog_article` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '自增id',
  `uid` int(10) NOT NULL COMMENT '用户id',
  `title` varchar(255) NOT NULL COMMENT '标题',
  `content` longtext NOT NULL COMMENT '内容',
  `keyword` varchar(255) DEFAULT NULL COMMENT '文章标签',
  `sortid` int(10) NOT NULL DEFAULT '0' COMMENT '分类',
  `img` varchar(255) DEFAULT NULL COMMENT '文章配图',
  `views` int(10) NOT NULL DEFAULT '0' COMMENT '阅读量',
  `comnum` int(10) NOT NULL DEFAULT '0' COMMENT '评论数',
  `topway` enum('none','sort','home') DEFAULT 'none',
  `status` enum('hide','show') DEFAULT NULL,
  `datetime` datetime NOT NULL COMMENT '创建时间',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=96 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of blog_article
-- ----------------------------
INSERT INTO `blog_article` VALUES ('59', '1', '8个最佳Web开发资源推荐', '<p>Web开发对程序员来说是一项较为复杂的工作，程序员需要快速地满足用户需求。如今很多的在线资源可以给程序员提供帮助，比如指导手册、在线课程和一些参考资料，而且这些资源基本都是免费和适合初学者的。无论你是需要选择一门新的编程语言，或是了解最新的标准，还是需要从其他地方找到一些灵感，我们这里为你整理了一些很好的Web开发资源，帮助你更成功地进行Web开发。在PHP开发中,比起Cookie，Session 是存储在服务器端的会话，相对安全，并且不像 Cookie 那样有存储长度限制，这里我们详细介绍一下PHP处理会话函数将要用到10个函数。<br/></p>', 'web，开发', '7', null, '1', '0', 'sort', 'show', '2015-05-21 14:18:54');
INSERT INTO `blog_article` VALUES ('3', '1', 'PHP中的一些会话技术与函数', '<p>在PHP开发中,比起Cookie，Session 是存储在服务器端的会话，相对安全，并且不像 Cookie 那样有存储长度限制，这里我们详细介绍一下PHP处理会话函数将要用到10个函数。在PHP开发中,比起Cookie，Session 是存储在服务器端的会话，相对安全，并且不像 Cookie 那样有存储长度限制，这里我们详细介绍一下PHP处理会话函数将要用到10个函数。在PHP开发中,比起Cookie，Session 是存储在服务器端的会话，相对安全，并且不像 Cookie 那样有存储长度限制，这里我们详细介绍一下PHP处理会话函数将要用到10个函数。PHP开发中,比起Cookie，Session 是存储在服务器端的会话，相对安全，并且不像 Cookie 那样有存储长度限制，这里我们详细介绍一下PHP处理会话函数将要用到10个函数。在PHP开发中,比起Cookie，Session 是存储在服务器端的会话，相对安全，并且不像 Cookie 那样有存储长度限制，这里我们详细介绍一下PHP处理会话函数将要用到10个函数。在PHP开发中,比起Cookie，Session 是存储在服务器端的会话，相对安全，并且不像 Cookie 那样有存储长度限制，这里我们详细介绍一下PHP处理会话函数将要用到10个函数。PHP开发中,比起Cookie，Session 是存储在服务器端的会话，相对安全，并且不像 Cookie 那样有存储长度限制，这里我们详细介绍一下PHP处理会话函数将要用到10个函数。在PHP开发中,比起Cookie，Session 是存储在服务器端的会话，相对安全，并且不像 Cookie 那样有存储长度限制，这里我们详细介绍一下PHP处理会话函数将要用到10个函数。在PHP开发中,比起Cookie，Session 是存储在服务器端的会话，相对安全，并且不像 Cookie 那样有存储长度限制，这里我们详细介绍一下PHP处理会话函数将要用到10个函数。下PHP处理会话函数将要用到10个函数。<br/></p>', 'php，会话技术，函数，cookie，session', '6', null, '2', '0', 'sort', 'show', '2014-11-18 03:33:00');
INSERT INTO `blog_article` VALUES ('4', '2', 'PHP框架推荐与说明。', '<p> PHP成为最流行的脚本语言有许多原因：灵活性，易用性等等。对于项目开发来说，我们通常需要一个PHP框架来代替程序员完成那些重复的部分。本文将对PHP框架进行全面解析。PHP成为最流行的脚本语言有许多原因：灵活性，易用性等等。对于项目开发来说，我们通常需要一个PHP框架来代替程序员完成那些重复的部分。本文将对PHP框架进行全面解析。<br/></p>', 'php，框架', '6', null, '12', '0', 'home', 'show', '2014-12-15 03:53:00');
INSERT INTO `blog_article` VALUES ('5', '1', '16个最佳响应式HTML5框架分享8个最佳Web开发资源推荐', '<p>HTML5框架可以快速构建响应式网站，它们帮助程序员减少编码工作，减少冗余的代码。如今有很多免费的HTML5框架可供使用，由于它们有着响应式设计、跨浏览器兼容、相对轻量级等特点，这些框架在开发中都十分流行。在PHP开发中,比起Cookie，Session 是存储在服务器端的会话，相对安全，并且不像 Cookie 那样有存储长度限制，这里我们详细介绍一下PHP处理会话函数将要用到10个函数。PHP成为最流行的脚本语言有许多原因：灵活性，易用性等等。对于项目开发来说，我们通常需要一个PHP框架来代替程序员完成那些重复的部分。本文将对PHP框架进行全面解析。<br/></p>', 'html5，框架，响应式', '7', null, '40', '6', 'none', 'show', '2014-10-15 07:51:00');
INSERT INTO `blog_article` VALUES ('7', '1', 'VC的陷阱，看哪些条款会威胁到创业者的利益', '<p>我们在期待天使投资人真的如天使般善心，愿意长期扶助创业企业的同时，也要明确地认识到，有些投资人是单纯追求财务上的收益最大化的。残酷但合理。PHP成为最流行的脚本语言有许多原因：灵活性，易用性等等。对于项目开发来说，我们通常需要一个PHP框架来代替程序员完成那些重复的部分。本文将对PHP框架进行全面解析。<br/></p>', 'vc', '6', null, '0', '0', 'none', 'show', '2014-12-15 08:53:00');
INSERT INTO `blog_article` VALUES ('17', '1', 'PHP数组操作详解', '<p>概述要访问一个变量的内容，可以直接使用其名称。如果该变量是一个数组，可以使用变量名称和关键字或索引的组合来访问其内容。像其他变量一样，使用运算符=可以改变数组元素的内容。数组单元可以通过 PHP成为最流行的脚本语言有许多原因：灵活性，易用性等等。对于项目开发来说，我们通常需要一个PHP框架来代替程序员完成那些重复的部分。本文将对PHP框架进行全面解析。<br/></p>', 'php，数组，函数', '6', null, '19', '0', 'home', 'show', '2014-12-23 09:02:05');
INSERT INTO `blog_article` VALUES ('48', '1', '史上最狡猾恶意软件现身php：被发现后会自爆', '<p>它可以拦截任何输入浏览器窗口中的纯文本，如果在安全检查中被发现，会竭力毁掉计算机。PHP成为最流行的脚本语言有许多原因：灵活性，易用性等等。对于项目开发来说，我们通常需要一个PHP框架来代替程序员完成那些重复的部分。本文将对PHP框架进行全面解析。<br/></p>', 'php，软件，', '5', null, '0', '0', 'none', 'show', '2015-03-10 11:50:42');
INSERT INTO `blog_article` VALUES ('49', '1', 'Linux中如何找出系统所支持的最大内存', '<p>大多数情况下你可以从BIOS、产品目录或者干脆手动找出你的系统所持的最大内存。这里，我们介绍一种简单有用的技巧——使用dmidecode来找出系统支持的最大内存，这样你就无需打开机箱或者参照BIOS和产品目录了。PHP成为最流行的脚本语言有许多原因：灵活性，易用性等等。对于项目开发来说，我们通常需要一个PHP框架来代替程序员完成那些重复的部分。本文将对PHP框架进行全面解析。<br/></p>', 'linux，内存', '5', null, '0', '0', 'none', 'show', '2015-05-21 11:51:29');
INSERT INTO `blog_article` VALUES ('50', '1', '90后与大趋势，社交APP必须顺应的人性变革', '<p> 90后，何方神圣？近段时间以来，创投圈对90后有某种妖魔化或神圣化的趋势。特别是在社交这样说不清道不明的领域，很多人的态度就如同宗教一般的执迷，仿佛90后的就是看不懂的，但正因为看不懂，就恰恰代表了大商PHP成为最流行的脚本语言有许多原因：灵活性，易用性等等。对于项目开发来说，我们通常需要一个PHP框架来代替程序员完成那些重复的部分。本文将对PHP框架进行全面解析。<br/></p>', '90后，app', '2', null, '0', '0', 'none', 'show', '2015-02-17 11:57:16');
INSERT INTO `blog_article` VALUES ('51', '1', 'php程序员必须克服的十大编程禁忌', '<p>程序员在编程的时候难免会犯错误，但如果不从错误中吸取教训，那么习 惯成自然，你会经常犯错的。从错误中不断的学习，锻炼好的行为习惯有助于事业上的稳定。这就是我们如何将小麦从糟糠中区别出来以及如何避免编程禁忌的绝佳 经验。PHP成为最流行的脚本语言有许多原因：灵活性，易用性等等。对于项目开发来说，我们通常需要一个PHP框架来代替程序员完成那些重复的部分。本文将对PHP框架进行全面解析。<br/></p>', 'php，程序员，编程，禁忌', '6', null, '3', '0', 'none', 'show', '2015-05-21 14:01:44');
INSERT INTO `blog_article` VALUES ('52', '1', '70%的php优秀员工的离职原因', '<p>【高阅读量文章的标题怎么取?14种模板直接套用!】你有没有这样的困惑，做出了一篇超棒的内容，但阅读和传播量却少的可怜? 让我们来看看这几篇文章： 《烧纸钱的由来》、《Under Armour的营销策略》PHP成为最流行的脚本语言有许多原因：灵活性，易用性等等。对于项目开发来说，我们通常需要一个PHP框架来代替程序员完成那些重复的部分。本文将对PHP框架进行全面解析。<br/></p>', 'php，程序员，离职', '2', null, '1', '0', 'sort', 'show', '2015-04-01 14:02:06');
INSERT INTO `blog_article` VALUES ('53', '1', '八张图读懂未来“互联网+”的六大趋势', '<p>虽然“互联网”一词在当下伴随着鼓吹与泡沫而炙手可热，但毋庸置疑的是，互联网将成为人类下一次飞跃的桥梁和动力。今天我们将以八张图分析一下互联网发展的未来趋势。PHP成为最流行的脚本语言有许多原因：灵活性，易用性等等。对于项目开发来说，我们通常需要一个PHP框架来代替程序员完成那些重复的部分。本文将对PHP框架进行全面解析。<br/></p>', '互联网，趋势', '2', null, '2', '1', 'none', 'show', '2015-05-21 14:02:16');
INSERT INTO `blog_article` VALUES ('54', '1', '如何不用重启在CentOS 7/ RHEL 7虚拟机中添加一块新硬盘', '<p> 通常在你在虚拟机中添加一块新硬盘时，你可能会看到新硬盘没有自动加载。这是因为连接到硬盘的SCSI总线需要重新扫描来使得新硬盘可见。这里有一个简单的命令来重新扫描SCSI总线和SCSI设备。下面这几步在CentOSPHP成为最流行的脚本语言有许多原因：灵活性，易用性等等。对于项目开发来说，我们通常需要一个PHP框架来代替程序员完成那些重复的部分。本文将对PHP框架进行全面解析。<br/></p>', 'CentOS，RHEL，Linux', '5', null, '0', '1', 'none', 'show', '2015-06-01 14:02:24');
INSERT INTO `blog_article` VALUES ('55', '1', '为了拯救手机续航 前沿电池技术来了', '<p>在过去的几天里，我们讨论了一些有关于电池技术的问题，比如为什么智能手机和平板电脑的计算效能进步的如此之快，而电池技术却仿佛止步不前；以及手机续航差竟然是软件开发者的问题，因为他们的应用中含有大量无用的代码浪费了手机的能源和通讯资源。PHP成为最流行的脚本语言有许多原因：灵活性，易用性等等。对于项目开发来说，我们通常需要一个PHP框架来代替程序员完成那些重复的部分。本文将对PHP框架进行全面解析。<br/></p>', '手机，续航，电池', '2', null, '0', '3', 'sort', 'show', '2015-06-01 14:04:42');
INSERT INTO `blog_article` VALUES ('56', '1', '10 个优秀的JavaScript开发框架', '<p>JavaScript基本上是一个面向对象的脚本语言，创建web应用程序和互动网站。Javascript框架也被称为Javascript库。JavaScript框架很容易提高设计web开发工作,提供了许多特性和功能,从而帮助开发人员提高网站开发任 PHP成为最流行的脚本语言有许多原因：灵活性，易用性等等。对于项目开发来说，我们通常需要一个PHP框架来代替程序员完成那些重复的部分。本文将对PHP框架进行全面解析。<br/></p>', 'JavaScript，框架，前端', '7', null, '0', '0', 'none', 'show', '2015-07-22 14:10:27');
INSERT INTO `blog_article` VALUES ('57', '1', '15个关于HTML的入门问题', '<p>超文本标记语言，即我们常说的HTML，是一种用来制作网页的标准标记语言，它是由一系列的HTML标签构成。HTML标签大多都是成对出现的，比如，分别是开始标记和结束标记。但也有一些标签是没有内容的，也就没有结束标记，比如。PHP成为最流行的脚本语言有许多原因：灵活性，易用性等等。对于项目开发来说，我们通常需要一个PHP框架来代替程序员完成那些重复的部分。本文将对PHP框架进行全面解析。</p>', 'html', '7', null, '37', '0', 'home', 'show', '2015-07-22 14:10:27');
INSERT INTO `blog_article` VALUES ('58', '1', 'php程序员值得关注的12个国外博客', '<p>开发软件需要考虑很多事情，没有你想的那么简单。随着你做的东西越来越多，你就会发现你有更多的东西需要去学习。虽然有很多开发者在分享他们的经验，但你也不可能全部照搬，很难选择。正因如此，我们收集了下面这12个技术型博客，希望可以给你的开发提供帮助。PHP成为最流行的脚本语言有许多原因：灵活性，易用性等等。对于项目开发来说，我们通常需要一个PHP框架来代替程序员完成那些重复的部分。本文将对PHP框架进行全面解析。<br/></p>', 'php，程序员，博客', '6', null, '14', '0', 'none', 'show', '2015-08-26 14:18:31');
INSERT INTO `blog_article` VALUES ('60', '1', 'PHP7性能提升之后的思考', '<p>时下不少人拿PHP7的高性能与HHVM来做比较，那么问题来了：随着PHP7性能的提升，我们能预测出未来PHP这门语言会用PHP写出来么？最经典的实例就是PyPy，这是一个用RPython（Python的一个子集）写出来的Python解释器和实时编译器。PHP成为最流行的脚本语言有许多原因：灵活性，易用性等等。对于项目开发来说，我们通常需要一个PHP框架来代替程序员完成那些重复的部分。本文将对PHP框架进行全面解析。时下不少人拿PHP7的高性能与HHVM来做比较，那么问题来了：随着PHP7性能的提升，我们能预测出未来PHP这门语言会用PHP写出来么？最经典的实例就是PyPy，这是一个用RPython（Python的一个子集）写出来的Python解释器和实时编译器。PHP成为最流行的脚本语言有许多原因：灵活性，易用性等等。对于项目开发来说，我们通常需要一个PHP框架来代替程序员完成那些重复的部分。本文将对PHP框架进行全面解析。时下不少人拿PHP7的高性能与HHVM来做比较，那么问题来了：随着PHP7性能的提升，我们能预测出未来PHP这门语言会用PHP写出来么？最经典的实例就是PyPy，这是一个用RPython（Python的一个子集）写出来的Python解释器和实时编译器。PHP成为最流行的脚本语言有许多原因：灵活性，易用性等等。对于项目开发来说，我们通常需要一个PHP框架来代替程序员完成那些重复的部分。本文将对PHP框架进行全面解析。时下不少人拿PHP7的高性能与HHVM来做比较，那么问题来了：随着PHP7性能的提升，我们能预测出未来PHP这门语言会用PHP写出来么？最经典的实例就是PyPy，这是一个用RPython（Python的一个子集）写出来的Python解释器和实时编译器。PHP成为最流行的脚本语言有许多原因：灵活性，易用性等等。对于项目开发来说，我们通常需要一个PHP框架来代替程序员完成那些重复的部分。本文将对PHP框架进行全面解析。时下不少人拿PHP7的高性能与HHVM来做比较，那么问题来了：随着PHP7性能的提升，我们能预测出未来PHP这门语言会用PHP写出来么？最经典的实例就是PyPy，这是一个用RPython（Python的一个子集）写出来的Python解释器和实时编译器。PHP成为最流行的脚本语言有许多原因：灵活性，易用性等等。对于项目开发来说，我们通常需要一个PHP框架来代替程序员完成那些重复的部分。本文将对PHP框架进行全面解析。时下不少人拿PHP7的高性能与HHVM来做比较，那么问题来了：随着PHP7性能的提升，我们能预测出未来PHP这门语言会用PHP写出来么？最经典的实例就是PyPy，这是一个用RPython（Python的一个子集）写出来的Python解释器和实时编译器。PHP成为最流行的脚本语言有许多原因：灵活性，易用性等等。对于项目开发来说，我们通常需要一个PHP框架来代替程序员完成那些重复的部分。本文将对PHP框架进行全面解析。</p>', 'php7，性能', '6', null, '17', '1', 'none', 'show', '2015-08-26 14:18:31');
INSERT INTO `blog_article` VALUES ('64', '1', 'PHP学习好文回顾推荐', '<p>过年福利（PHP学习好文推荐），PHP100为大家从PHP认知、学习、深入、资料和线路五个方面，汇总相关好文推荐，帮助你更好的了解和学习PHP。PHP成为最流行的脚本语言有许多原因：灵活性，易用性等等。对于项目开发来说，我们通常需要一个PHP框架来代替程序员完成那些重复的部分。本文将对PHP框架进行全面解析。<br/></p>', 'php，文章', '6', null, '28', '3', 'sort', 'show', '2014-01-12 16:47:55');
INSERT INTO `blog_article` VALUES ('65', '1', 'PHP实现四种基本排序算法', '<p>许多人都说算法是程序的核心，算法的好坏决定了程序的质量。作为一个初级phper，虽然很少接触到算法方面的东西。但是对于基本的排序算法还是应该掌握的，它是程序开发的必备工具。这里介绍冒泡排序，插入排序，选择排序，快速排序四种基本算法，分析一下算法的思路。PHP成为最流行的脚本语言有许多原因：灵活性，易用性等等。对于项目开发来说，我们通常需要一个PHP框架来代替程序员完成那些重复的部分。本文将对PHP框架进行全面解析。</p>', 'php，排序，算法', '6', null, '1', '0', 'none', 'show', '2014-01-12 16:47:55');
INSERT INTO `blog_article` VALUES ('63', '1', 'php使用AngularJS创建应用的5个框架', '<p>如果你计划使用AngularJS创建你的Web应用，那现在就开始吧。你不需要有任何的恐惧和担心，因为现在有很多的框架都可以很好地支持AngularJS。这些框架都有事先安装的Web组件，使用它们可以帮助你快速进行项目开发。这里列举5个这样的框架，帮助你使用AngularJS构建Web应用。PHP成为最流行的脚本语言有许多原因：灵活性，易用性等等。对于项目开发来说，我们通常需要一个PHP框架来代替程序员完成那些重复的部分。本文将对PHP框架进行全面解析。<br/></p>', 'php，AngularJS，JavaScript', '6', null, '0', '0', 'sort', 'show', '2015-05-25 16:46:42');
INSERT INTO `blog_article` VALUES ('66', '1', 'SQL命令及phpMyAdmin操作介绍', '<p>hpMyAdmin是一个非常受欢迎的基于web的MySQL数据库管理工具。它能够创建和删除数据库，创建 删除 修改表格,删除 编辑 新增字段，执行SQL脚本等。PHP成为最流行的脚本语言有许多原因：灵活性，易用性等等。对于项目开发来说，我们通常需要一个PHP框架来代替程序员完成那些重复的部分。本文将对PHP框架进行全面解析。</p>', 'mysql，phpMyAdmin', '4', null, '11', '2', 'home', 'show', '2014-06-11 16:47:55');
INSERT INTO `blog_article` VALUES ('67', '1', '为php开发者准备的10款错误报告和追踪工具', '<p>在程序开发中，快速有效的找到代码中的错误并给予解决是十分重要的技能，也就是调试代码的能力。我们要在实现、测试中确保代码的质量，无论错误的大小，Web开发者都应该可以追踪代码，找到错误。当然，可以借助一些优秀的代码调试工具是最好不过的了。PHP成为最流行的脚本语言有许多原因：灵活性，易用性等等。对于项目开发来说，我们通常需要一个PHP框架来代替程序员完成那些重复的部分。本文将对PHP框架进行全面解析。</p>', 'php，开发，工具', '6', null, '19', '5', 'none', 'show', '2015-05-26 13:58:00');
INSERT INTO `blog_article` VALUES ('70', '1', '哈哈天天开心是傻瓜，哇哈哈', '<p>影子是一个会撒谎的精灵，它在虚空中流浪和等待被发现之间;在存在与不存在之间APHP成为最流行的脚本语言有许多原因：灵活性，易用性等等。对于项目开发来说，我们通常需要一个PHP框架来代替程序员完成那些重复的部分。本文将对PHP框架进行全面解析。</p>', null, '2', null, '14', '7', 'home', 'show', '2014-06-26 16:47:55');
INSERT INTO `blog_article` VALUES ('69', '1', '黑色Html5个人博客模板主题sss8个最佳Web开发资源推荐', '<p>第二版黑色Html5个人博客模板主题《如影随形》，如精灵般的影子会给人一种神秘的感觉。一张剪影图黑白搭配，如果整个网站用黑白灰三色，会显得比较太过沉重，于是，在选择亮色方面，用以红为主色，蓝为辅色。这样就铺上了一些神秘甚至有些俏皮的元素。\r\n\r\n如果你更喜欢用蓝色或者绿色，这也不错，替换关键的颜色值就行了，推荐颜色值<br/></p><p>  </p>', 'html，模板，页面，php', '7', null, '900', '45', 'none', 'show', '2014-01-12 16:47:55');
INSERT INTO `blog_article` VALUES ('75', '1', 'php 上传cvs文件并读取，重新生成cvs文件', '<pre class=\\\"brush:php;toolbar:false\\\"></pre><pre>&lt;?php//校验上传文件类型if(empty($_FILES[&#39;csv&#39;][&#39;error&#39;]))&nbsp;{&nbsp;&nbsp;&nbsp;&nbsp;$sFileExt&nbsp;=&nbsp;strtolower(substr($_FILES[&#39;csv&#39;][&#39;name&#39;],&nbsp;-3));&nbsp;//获取后缀名\r\n&nbsp;&nbsp;&nbsp;&nbsp;if($sFileExt&nbsp;!=&nbsp;&#39;csv&#39;){\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Page::error(&#39;上传文件必须是csv文件&#39;);\r\n&nbsp;&nbsp;&nbsp;&nbsp;}&nbsp;&nbsp;&nbsp;&nbsp;$sFileName&nbsp;=&nbsp;$_FILES[&#39;csv&#39;][&#39;tmp_name&#39;];&nbsp;&nbsp;&nbsp;&nbsp;$oFile&nbsp;=&nbsp;fopen&#40;$sFileName,&nbsp;&#39;r&#39;&#41;;&nbsp;&nbsp;&nbsp;&nbsp;$aSameNick&nbsp;=&nbsp;array();&nbsp;&nbsp;&nbsp;&nbsp;while(($aRow&nbsp;=&nbsp;fgetcsv($oFile,&nbsp;10000))&nbsp;!==&nbsp;false)&nbsp;{&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$list[]&nbsp;=&nbsp;$aRow;\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n&nbsp;&nbsp;&nbsp;&nbsp;}&nbsp;&nbsp;&nbsp;&nbsp;fclose($oFile);&nbsp;&nbsp;&nbsp;&nbsp;\r\n&nbsp;&nbsp;&nbsp;&nbsp;//确定文件名\r\n&nbsp;&nbsp;&nbsp;&nbsp;$sFilename&nbsp;=&nbsp;&quot;cvs生成_&quot;&nbsp;.&nbsp;time().&nbsp;&quot;.csv&quot;;&nbsp;&nbsp;&nbsp;&nbsp;$sFilename&nbsp;=&nbsp;mb_convert_encoding($sFilename,&nbsp;&#39;gbk&#39;);&nbsp;&nbsp;&nbsp;&nbsp;header(&quot;Content-type:application/vnd.ms-excel&quot;);&nbsp;&nbsp;&nbsp;&nbsp;header(&quot;Content-Disposition:filename=&quot;&nbsp;.&nbsp;$sFilename);&nbsp;&nbsp;&nbsp;&nbsp;//导出生成的短链接\r\n&nbsp;&nbsp;&nbsp;&nbsp;$sOut&nbsp;=&nbsp;&quot;手机,短链接,长链接,姓名,userid&quot;.&quot;\\\\n&quot;;&nbsp;&nbsp;&nbsp;&nbsp;$sOut&nbsp;=&nbsp;mb_convert_encoding($sOut,&nbsp;&#39;gbk&#39;);&nbsp;&nbsp;&nbsp;&nbsp;echo&nbsp;$sOut;&nbsp;\r\n&nbsp;&nbsp;&nbsp;&nbsp;foreach($arr&nbsp;as&nbsp;$key&nbsp;=&gt;&nbsp;$val){&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$sOut&nbsp;=&nbsp;&quot;\\\\&quot;{$mobile}\\\\&quot;,&quot;&nbsp;.\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;\\\\&quot;{$valurl_short}\\\\&quot;,&quot;&nbsp;.\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;\\\\&quot;{$valurl_real}\\\\&quot;,&quot;&nbsp;.\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;\\\\&quot;{$valuserName}\\\\&quot;,&quot;&nbsp;.\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;\\\\&quot;{$valuserId}\\\\&quot;,\\\\n&quot;;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$sOut&nbsp;=&nbsp;mb_convert_encoding($sOut,&nbsp;&#39;gbk&#39;);&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;echo&nbsp;$sOut;\r\n&nbsp;&nbsp;&nbsp;&nbsp;}\r\n}?&gt;</pre><p><br/></p>', 'php，cvs，上传', '6', null, '4', '0', 'none', 'show', '2015-07-10 10:15:32');
INSERT INTO `blog_article` VALUES ('77', '1', 'JavaScript测试', '<p>   </p><pre class=\\\"\\\\\\\\\\\\\\\\\\\">&lt;script&gt;\r\nalert&#40;111&#41;;\r\n$(&quot;.cleditor&quot;).cleditor({\r\n&nbsp;&nbsp;&nbsp;&nbsp;width:&nbsp;&quot;auto&quot;,\r\n&nbsp;&nbsp;&nbsp;&nbsp;height:&nbsp;&quot;auto&quot;\r\n});\r\n&lt;/script&gt;</pre><pre class=\\\"brush:diff;toolbar:false\\\">&lt;html&gt;\r\n&lt;head&gt;\r\n&nbsp;&nbsp;&nbsp;&nbsp;&lt;title&gt;HTML测试&lt;/title&gt;\r\n&lt;/head&gt;\r\n&lt;body&gt;\r\n&nbsp;&nbsp;&nbsp;&nbsp;&lt;h1&gt;test,test,test,test&lt;/h1&gt;\r\n&lt;/body&gt;\r\n&lt;/html&gt;</pre><pre class=\\\"brush:php;toolbar:false\\\">&nbsp;//递归取得下层文件夹下的文件&nbsp;&nbsp;\r\nfunction&nbsp;openFile&#40;$path,$zipName&#41;{\r\n&nbsp;&nbsp;&nbsp;&nbsp;$temp_path&nbsp;=&nbsp;$path;\r\n&nbsp;&nbsp;&nbsp;&nbsp;$temp_zip_path&nbsp;=&nbsp;$zipName;\r\n&nbsp;&nbsp;&nbsp;&nbsp;if($handle&nbsp;=&nbsp;@opendir($path)){\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;while(false&nbsp;!==&nbsp;($file&nbsp;=&nbsp;readdir($handle)))&nbsp;{\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if($file&nbsp;!=&#39;.&#39;&nbsp;&amp;&amp;&nbsp;$file&nbsp;!=&#39;..&#39;)&nbsp;{\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if(ereg(&#39;\\\\.&#39;&nbsp;,$file.@basename()))&nbsp;{\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$fd&nbsp;=&nbsp;fopen&#40;$path.&#39;/&#39;.$file,&quot;r&quot;&#41;;\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$fileValue&nbsp;=&nbsp;@fread($fd,1024000);\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;fclose&nbsp;($fd);\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$this&nbsp;-&gt;&nbsp;addFile&#40;$fileValue,$path.&#39;/&#39;.$file&#41;;\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}&nbsp;else&nbsp;{\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$this&nbsp;-&gt;openFile&#40;$path.&#39;/&#39;.$file,$zipName.&#39;/&#39;.$file&#41;;&nbsp;&nbsp;\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}\r\n&nbsp;&nbsp;&nbsp;&nbsp;$zipName=$temp_zip_path;&nbsp;&nbsp;\r\n&nbsp;&nbsp;&nbsp;&nbsp;$path&nbsp;=&nbsp;$temp_path;&nbsp;&nbsp;\r\n&nbsp;&nbsp;&nbsp;&nbsp;closedir($handle);&nbsp;&nbsp;\r\n&nbsp;&nbsp;&nbsp;&nbsp;}\r\n}</pre><p>  \r\n   </p>', '王永东', '7', '', '46', '0', 'none', 'show', '2015-07-15 13:55:07');
INSERT INTO `blog_article` VALUES ('88', '1', '人生困局a', '<p>   </p><p>年纪轻轻但在电影圈浸淫多年的新朋友，有一个古色古香的名字：凤兮。她趁周末到访，和我无拘无束地聊天。凤兮思想敏锐，思考的深度远非一般忙于上微信撒娇或讨论整容的“80后”可比。关于他们这一代的人生，\r\n她举了一个实例：波士顿一位白人女子，名叫玛丽，出生于富裕人家，家长是虔诚的基督徒。她自幼受完整的宗教熏陶，严守道德规范，举止庄重，言谈优雅。从幼\r\n儿时代起，她进的就是最好的教会学校。她智商超高，成绩从来不会是全校第三名以后。而且，在诸多课外活动中，她都是领导者、策划者。到了高中，她出落成明\r\n眸皓齿的美人、公认的校花。在所有人的称赞和爱护中，她一帆风顺地成长，每一步都走得稳妥而精彩，家里挂满上至州政府下至学校所颁发的奖状，古玩架上放满\r\n了她领到的奖杯。波澜不惊地走过少女的叛逆期，她考进常青藤名校，就读于生物系，以全优成绩取得硕士学位。离开大学校门那年，她24岁，不失时机地嫁给校\r\n友——毕业于同校法学院的英俊青年。幸运之舟在蔚蓝的宁静大海上航行，两年以后，她产下一个极可爱的胖小子。作为一名女性，拥有如此齐全的幸福，难道还有\r\n遗憾？</p><p>  \r\n   </p>', '搜索，哈哈', '2', '', '10', '7', 'none', 'show', '2015-08-06 14:49:11');
INSERT INTO `blog_article` VALUES ('93', '1', 'PHP的静态方法介绍', '<p>静态方法的规则和静态变量是相同的。使用ststic关键字可以将方法标识为静态方法，通过类的名称和作用域限定操作符::可以访问静态方法。</p><p>&nbsp;\r\n &nbsp; </p><p>静态方法和非静态方法之间有一个很重要的区别，就是在调用静态方法时，我们不需要创建类的实例。</p><h4>Program List：用类名作为参数</h4><p>用类名作为参数可以解决非继承的静态问题。</p><pre class=\\\"brush:php;toolbar:false\\\">&lt;?php\r\nclass&nbsp;Fruit&nbsp;{\r\n public&nbsp;static&nbsp;$category&nbsp;=&nbsp;&quot;I&#39;m&nbsp;fruit&quot;;\r\n&nbsp;&nbsp;&nbsp;&nbsp;\r\n&nbsp;&nbsp;&nbsp;&nbsp;static&nbsp;function&nbsp;find($class)&nbsp;\r\n {\r\n&nbsp;&nbsp;&nbsp;&nbsp; $vars&nbsp;=&nbsp;get_class_vars($class)&nbsp;;\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; echo&nbsp;$vars[&#39;category&#39;]&nbsp;;\r\n&nbsp;&nbsp;&nbsp;&nbsp;}\r\n}\r\n\r\nclass&nbsp;Apple&nbsp;extends&nbsp;Fruit&nbsp;{\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;public&nbsp;static&nbsp;$category&nbsp;=&nbsp;&quot;I&#39;m&nbsp;Apple&quot;;\r\n}\r\n\r\nApple::find(&quot;Apple&quot;);\r\n?&gt;</pre><p>程序运行结果：</p><table><tbody><tr><td class=\\\"number\\\"><code>1</code></td><td class=\\\"content\\\"><code class=\\\"plain\\\">I&#39;m Apple</code></td></tr></tbody></table><p><br/></p>', 'php,static', '6', '', '14', '0', 'none', 'show', '2015-08-24 11:03:12');
